-- ============================================================
-- Merry's Way Coffee Shop - Supabase schema (single source of truth)
-- ============================================================
-- FRESH INSTALL: run this whole file once in the Supabase SQL editor.
-- EXISTING PROJECT: run reset_schema.sql first. That DELETES ALL APP DATA
-- (profiles, orders, chat history, products). Auth users are kept.
--
-- After running it:
--   cd backend
--   uv run python scripts/seed_products.py     # menu + embeddings
--   uv run python scripts/index_metadata.py    # BI schema metadata
--   then make yourself admin (see the bottom of this file)
--
-- Conventions
--   user_email   : lowercase email is the user key everywhere
--   session_id   : UUID generated by the frontend
--   orders       : header in coffee_shop_orders, lines in coffee_shop_order_items
--   status       : 'pending' (live cart) | 'confirmed'; cancelled carts are deleted
--
-- Security model
--   * The backend uses the SERVICE ROLE key for all database access (the
--     frontend never talks to the database directly) and the service role
--     bypasses RLS. So NO table lets end users write; they can only read their
--     own rows if they ever call the REST API directly.
--   * Internal functions (cart, chat append, SQL runner, schema search) are
--     callable by the service role only.
-- ============================================================

create extension if not exists vector;


-- ── Helpers ───────────────────────────────────────────────────────────────────

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ── Profiles (preferences, allergies, admin flag) ─────────────────────────────

create table if not exists coffee_shop_profiles (
  user_email    text         primary key check (user_email = lower(user_email)),
  name          text,
  likes         jsonb        not null default '[]',
  dislikes      jsonb        not null default '[]',
  allergies     jsonb        not null default '[]',
  last_order    text,
  feedback      jsonb        not null default '[]',
  location      text,
  is_admin      boolean      not null default false,
  created_at    timestamptz  not null default now(),
  last_updated  timestamptz  not null default now()
);

alter table coffee_shop_profiles enable row level security;

drop policy if exists "Users can read own profile" on coffee_shop_profiles;
create policy "Users can read own profile"
  on coffee_shop_profiles for select
  using (lower(auth.jwt() ->> 'email') = user_email);
-- No insert/update/delete policies on purpose: users must not be able to edit
-- their own is_admin flag. The backend (service role) writes profiles.


-- ── Products (menu) ───────────────────────────────────────────────────────────

create table if not exists coffee_shop_products (
  id           uuid         primary key default gen_random_uuid(),
  name         text         not null unique,
  category     text,
  description  text,
  price        float        not null check (price >= 0),
  rating       float,
  ingredients  jsonb        not null default '[]',
  image_url    text,
  embedding    vector(768),
  created_at   timestamptz  not null default now()
);

-- Cart functions match product names case-insensitively, so keep them unique that way too.
create unique index if not exists coffee_shop_products_name_lower_idx
  on coffee_shop_products (lower(name));

alter table coffee_shop_products enable row level security;

drop policy if exists "Public can read products" on coffee_shop_products;
create policy "Public can read products"
  on coffee_shop_products for select
  using (true);

-- Semantic menu search used by the RAG tools (src/rag/retriever.py).
create or replace function match_coffee_products(
  query_embedding  vector(768),
  match_threshold  float,
  match_count      int
)
returns table (
  id           uuid,
  name         text,
  category     text,
  description  text,
  price        float,
  rating       float,
  ingredients  jsonb,
  image_url    text,
  similarity   float
)
language sql
stable
as $$
  select p.id, p.name, p.category, p.description, p.price, p.rating,
         p.ingredients, p.image_url,
         1 - (p.embedding <=> query_embedding) as similarity
  from coffee_shop_products p
  where p.embedding is not null
    and 1 - (p.embedding <=> query_embedding) > match_threshold
  order by p.embedding <=> query_embedding
  limit match_count;
$$;


-- ── Orders: header + line items ───────────────────────────────────────────────

create table if not exists coffee_shop_orders (
  id            uuid           primary key default gen_random_uuid(),
  user_email    text           not null references coffee_shop_profiles(user_email) on delete cascade,
  status        text           not null default 'pending' check (status in ('pending', 'confirmed')),
  total         numeric(10,2)  not null default 0 check (total >= 0),
  created_at    timestamptz    not null default now(),
  confirmed_at  timestamptz,
  updated_at    timestamptz    not null default now(),
  check ((status = 'confirmed') = (confirmed_at is not null))
);

-- At most ONE pending cart per user.
create unique index if not exists coffee_shop_orders_one_pending_per_user
  on coffee_shop_orders (user_email) where status = 'pending';
create index if not exists coffee_shop_orders_user_status_idx
  on coffee_shop_orders (user_email, status);
create index if not exists coffee_shop_orders_status_confirmed_idx
  on coffee_shop_orders (status, confirmed_at);

drop trigger if exists coffee_shop_orders_set_updated_at on coffee_shop_orders;
create trigger coffee_shop_orders_set_updated_at
  before update on coffee_shop_orders
  for each row execute function set_updated_at();

alter table coffee_shop_orders enable row level security;

drop policy if exists "Users can read own orders" on coffee_shop_orders;
create policy "Users can read own orders"
  on coffee_shop_orders for select
  using (lower(auth.jwt() ->> 'email') = user_email);
-- No write policies: otherwise a user could mark their own order 'confirmed'
-- or change its total through the REST API without paying.


create table if not exists coffee_shop_order_items (
  id            uuid           primary key default gen_random_uuid(),
  order_id      uuid           not null references coffee_shop_orders(id) on delete cascade,
  product_id    uuid           references coffee_shop_products(id) on delete set null,
  product_name  text           not null,
  quantity      integer        not null check (quantity > 0),
  unit_price    numeric(10,2)  not null check (unit_price >= 0),   -- price at order time
  line_total    numeric(10,2)  not null check (line_total >= 0),
  image_url     text,
  line_no       integer        not null default 0,
  unique (order_id, product_id)
);

create index if not exists coffee_shop_order_items_order_idx
  on coffee_shop_order_items (order_id);
create index if not exists coffee_shop_order_items_product_idx
  on coffee_shop_order_items (product_id);

alter table coffee_shop_order_items enable row level security;

drop policy if exists "Users can read own order items" on coffee_shop_order_items;
create policy "Users can read own order items"
  on coffee_shop_order_items for select
  using (
    exists (
      select 1 from coffee_shop_orders o
      where o.id = coffee_shop_order_items.order_id
        and o.user_email = lower(auth.jwt() ->> 'email')
    )
  );


-- Atomically replace the user's pending cart. `p_items` is a JSON array of
-- {name, quantity}. Prices and images come from coffee_shop_products, so any
-- price a client sends is ignored. Returns the new order id, or NULL if the
-- cart ended up empty.
create or replace function replace_pending_order(p_user_email text, p_items jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email    text := lower(trim(p_user_email));
  v_order_id uuid;
  v_total    numeric(10,2);
begin
  perform pg_advisory_xact_lock(hashtext(v_email));

  insert into coffee_shop_profiles (user_email) values (v_email)
  on conflict (user_email) do nothing;

  delete from coffee_shop_orders
   where user_email = v_email and status = 'pending';

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return null;
  end if;

  insert into coffee_shop_orders (user_email, status, total)
  values (v_email, 'pending', 0)
  returning id into v_order_id;

  insert into coffee_shop_order_items
         (order_id, product_id, product_name, quantity, unit_price, line_total, image_url, line_no)
  select v_order_id,
         p.id,
         p.name,
         sum(q.qty)::int,
         p.price::numeric(10,2),
         round(p.price::numeric * sum(q.qty), 2),
         p.image_url,
         min(q.ord)::int
  from (
         select lower(t.elem->>'name') as lname,
                coalesce((t.elem->>'quantity')::numeric, 0)::int as qty,
                t.ord
         from jsonb_array_elements(p_items) with ordinality as t(elem, ord)
       ) q
  join coffee_shop_products p on lower(p.name) = q.lname
  where q.qty > 0
  group by p.id, p.name, p.price, p.image_url;

  select coalesce(sum(line_total), 0) into v_total
    from coffee_shop_order_items where order_id = v_order_id;

  if v_total <= 0 then
    delete from coffee_shop_orders where id = v_order_id;
    return null;
  end if;

  update coffee_shop_orders set total = v_total where id = v_order_id;

  return v_order_id;
end;
$$;


-- Confirm the user's pending order. If `p_items` is given, the cart is first
-- re-synced from it (priced live). Every line is then re-priced from the live
-- product table, so the stored total is authoritative. Returns
-- {order_id, total, items:[{name, quantity, per_unit_price, total_price, image_url}]}
-- or NULL if there is nothing to confirm.
create or replace function confirm_pending_order(p_user_email text, p_items jsonb default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email    text := lower(trim(p_user_email));
  v_order_id uuid;
  v_total    numeric(10,2);
  v_items    jsonb;
begin
  perform pg_advisory_xact_lock(hashtext(v_email));

  if p_items is not null then
    perform replace_pending_order(v_email, p_items);
  end if;

  select id into v_order_id
    from coffee_shop_orders
   where user_email = v_email and status = 'pending'
   order by updated_at desc
   limit 1
   for update;

  if v_order_id is null then
    return null;
  end if;

  update coffee_shop_order_items i
     set unit_price = p.price::numeric(10,2),
         line_total = round(p.price::numeric * i.quantity, 2)
    from coffee_shop_products p
   where i.order_id = v_order_id
     and i.product_id = p.id;

  select coalesce(sum(line_total), 0) into v_total
    from coffee_shop_order_items where order_id = v_order_id;

  if v_total <= 0 then
    return null;
  end if;

  update coffee_shop_orders
     set status = 'confirmed',
         total = v_total,
         confirmed_at = now()
   where id = v_order_id;

  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'name', product_name,
               'quantity', quantity,
               'per_unit_price', unit_price,
               'total_price', line_total,
               'image_url', image_url
             ) order by line_no
           ),
           '[]'::jsonb)
    into v_items
    from coffee_shop_order_items
   where order_id = v_order_id;

  return jsonb_build_object('order_id', v_order_id, 'total', v_total, 'items', v_items);
end;
$$;

revoke all on function replace_pending_order(text, jsonb) from public, anon, authenticated;
grant execute on function replace_pending_order(text, jsonb) to service_role;

revoke all on function confirm_pending_order(text, jsonb) from public, anon, authenticated;
grant execute on function confirm_pending_order(text, jsonb) to service_role;


-- ── Chat sessions (customer chat history) ─────────────────────────────────────

create table if not exists coffee_shop_sessions (
  session_id   uuid         primary key,
  user_email   text         not null references coffee_shop_profiles(user_email) on delete cascade,
  messages     jsonb        not null default '[]',
  created_at   timestamptz  not null default now(),
  last_active  timestamptz  not null default now()
);

create index if not exists coffee_shop_sessions_user_idx
  on coffee_shop_sessions (user_email, last_active desc);

alter table coffee_shop_sessions enable row level security;

drop policy if exists "Users can read own sessions" on coffee_shop_sessions;
create policy "Users can read own sessions"
  on coffee_shop_sessions for select
  using (lower(auth.jwt() ->> 'email') = user_email);

-- Atomic append (no read-modify-write race). Creates the session if needed and
-- only ever appends to a session owned by the same user.
create or replace function append_chat_messages(
  p_session_id    uuid,
  p_user_email    text,
  p_new_messages  jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(p_user_email));
begin
  insert into coffee_shop_profiles (user_email) values (v_email)
  on conflict (user_email) do nothing;

  insert into coffee_shop_sessions (session_id, user_email, messages)
  values (p_session_id, v_email, coalesce(p_new_messages, '[]'::jsonb))
  on conflict (session_id) do update
    set messages    = coffee_shop_sessions.messages || coalesce(excluded.messages, '[]'::jsonb),
        last_active = now()
    where coffee_shop_sessions.user_email = v_email;
end;
$$;

revoke all on function append_chat_messages(uuid, text, jsonb) from public, anon, authenticated;
grant execute on function append_chat_messages(uuid, text, jsonb) to service_role;


-- ── Admin BI ──────────────────────────────────────────────────────────────────

create table if not exists coffee_shop_admin_sessions (
  session_id  text         primary key,
  user_email  text         not null,
  history     jsonb        not null default '[]',
  updated_at  timestamptz  not null default now()
);

drop trigger if exists coffee_shop_admin_sessions_set_updated_at on coffee_shop_admin_sessions;
create trigger coffee_shop_admin_sessions_set_updated_at
  before update on coffee_shop_admin_sessions
  for each row execute function set_updated_at();

-- RLS on with no policies: only the backend (service role) can touch it.
alter table coffee_shop_admin_sessions enable row level security;


-- Schema metadata the BI agent searches to decide which tables/columns to use
-- (filled by scripts/index_metadata.py).
create table if not exists coffee_shop_schema_metadata (
  id         uuid         primary key default gen_random_uuid(),
  content    text         not null,
  metadata   jsonb        not null,
  embedding  vector(768)
);

alter table coffee_shop_schema_metadata enable row level security;

create or replace function match_schema_metadata(
  query_embedding  vector(768),
  match_threshold  float,
  match_count      int
)
returns table (
  id          uuid,
  content     text,
  metadata    jsonb,
  similarity  float
)
language sql
stable
as $$
  select m.id, m.content, m.metadata,
         1 - (m.embedding <=> query_embedding) as similarity
  from coffee_shop_schema_metadata m
  where 1 - (m.embedding <=> query_embedding) > match_threshold
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

revoke all on function match_schema_metadata(vector, float, int) from public, anon, authenticated;
grant execute on function match_schema_metadata(vector, float, int) to service_role;


-- Runs the Text-to-SQL agent's query. Defence in depth:
--   * callable by the service role only (NOT by logged-in users)
--   * a single SELECT/WITH statement only
--   * system schemas and pg_* functions are rejected
--   * the transaction is switched to READ ONLY, so any write fails even if the
--     checks above are bypassed
-- Errors are returned as [{"error": "..."}] so the agent can self-correct.
create or replace function execute_sql_query(sql_query text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if sql_query is null or sql_query !~* '^\s*(select|with)\s' then
    raise exception 'Only SELECT queries (read-only) are allowed for the BI agent.';
  end if;

  if position(';' in sql_query) > 0 then
    raise exception 'Multiple statements are not allowed.';
  end if;

  if sql_query ~* '(\mauth\.|\mpg_|\minformation_schema|\mstorage\.|\mvault\.|\mextensions\.)' then
    raise exception 'Access to system schemas is not allowed.';
  end if;

  perform set_config('transaction_read_only', 'on', true);

  execute format('select coalesce(jsonb_agg(t), ''[]''::jsonb) from (%s) t', sql_query)
    into result;
  return result;
exception when others then
  return jsonb_build_array(jsonb_build_object('error', sqlerrm));
end;
$$;

revoke all on function execute_sql_query(text) from public, anon, authenticated;
grant execute on function execute_sql_query(text) to service_role;


-- ── Storage buckets ───────────────────────────────────────────────────────────
-- product-images : menu photos (public)
-- chat_images    : images customers attach in chat (public URL, images only, 5 MB)
-- Wrapped so a storage-schema difference never aborts the rest of this file.
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do nothing;

  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('chat_images', 'chat_images', true, 5242880,
          array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
  on conflict (id) do nothing;
exception when others then
  raise notice 'Could not create storage buckets (%). Create product-images and chat_images in the dashboard.', sqlerrm;
end;
$$;


-- ── Backfill profiles for users who already signed up ─────────────────────────
-- Auth users survive a reset, but their profile rows do not. Recreate them.
do $$
begin
  insert into coffee_shop_profiles (user_email, name)
  select lower(u.email), u.raw_user_meta_data ->> 'username'
  from auth.users u
  where u.email is not null
  on conflict (user_email) do nothing;
exception when others then
  raise notice 'Could not backfill profiles from auth.users (%).', sqlerrm;
end;
$$;

notify pgrst, 'reload schema';


-- ============================================================
-- AFTER INSTALL
-- ============================================================
-- Make yourself the admin (use the email you log in with, lowercase):
--   update coffee_shop_profiles set is_admin = true where user_email = 'you@example.com';
--
-- Sanity checks:
--   select count(*) from coffee_shop_products;                     -- 58 after seeding
--   select count(*) from coffee_shop_products where embedding is not null;   -- 58
--   select proname, proacl from pg_proc
--    where proname in ('execute_sql_query','replace_pending_order','confirm_pending_order',
--                      'append_chat_messages','match_schema_metadata');
--   -- proacl must list service_role only (no =X/ public entry, no anon, no authenticated)
